### ISSUE TITLE
Execute only one test - the changed test

### ISSUE THREAD

**Issue by naxmefy** [Rowno/grunt-mocha-cli#21]
Specified this:

```
module.exports = (grunt)->
  grunt.initConfig
    watch:
      coffee:
        files: ['test/**/*.coffee', 'common/**/*.coffee'] # TODO Other SubApps too...
        tasks: ['mochacli'] #'clear', 

    mochacli:
      options:
        reporter: 'list'
        compilers: ['coffee:coffee-script/register']
        require: ['should']
        ui: 'bdd'
        env:
          NODE_ENV: 'test'
      all: ['test/**/*.coffee']
```

Here primary problem!

```
  grunt.event.on 'watch', (action, filePath)->
    if grunt.file.isMatch grunt.config('watch.coffee.files'), filePath
      console.log 'Action: '+action
      console.log 'FilePath: '+filePath
      if grunt.file.isMatch grunt.config('mochacli.all'), filePath
        console.log 'MochaCLI Config: '
        console.log grunt.config 'mochacli'
        grunt.config 'mochacli.all', [filePath]
        console.log 'MochaCLI Config: '
        console.log grunt.config 'mochacli'
    else
      console.log 'Wrong FilePath: ' + filePath
```

```
  grunt.loadNpmTasks 'grunt-contrib-watch'
  grunt.loadNpmTasks 'grunt-mocha-cli'
  grunt.loadNpmTasks 'grunt-clear'

  grunt.registerTask 'default'
  grunt.registerTask 'test', ['mochacli']
  grunt.registerTask 'test-watcher', ['watch:coffee']
```
- Event is called
- Config is changed

= But i executes all tests...why? :(

if mochacli.all is empty - nothing will be executed
tried with files and filesraw - didnt work
- [grunt-newer](https://github.com/tschaub/grunt-newer) also failed
